// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/qwerq.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishRequest is sent by client to publish a message.
type PublishRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Queue          string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MessageId      *string                `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`                // Client-provided, or broker generates
	IdempotencyKey *string                `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"` // For deduplication
	OrderingKey    string                 `protobuf:"bytes,6,opt,name=ordering_key,json=orderingKey,proto3" json:"ordering_key,omitempty"`                // Optional: messages with same key go to same consumer
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_qwerq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PublishRequest) GetMessageId() string {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return ""
}

func (x *PublishRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *PublishRequest) GetOrderingKey() string {
	if x != nil {
		return x.OrderingKey
	}
	return ""
}

// PublishResponse confirms a publish.
type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_qwerq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// ConsumeRequest starts consuming from a queue.
type ConsumeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Queue             string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Prefetch          uint32                 `protobuf:"varint,2,opt,name=prefetch,proto3" json:"prefetch,omitempty"`                                            // Max unacked messages (default 1)
	VisibilityTimeout uint32                 `protobuf:"varint,3,opt,name=visibility_timeout,json=visibilityTimeout,proto3" json:"visibility_timeout,omitempty"` // Seconds before redelivery (default 30)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_proto_qwerq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ConsumeRequest) GetPrefetch() uint32 {
	if x != nil {
		return x.Prefetch
	}
	return 0
}

func (x *ConsumeRequest) GetVisibilityTimeout() uint32 {
	if x != nil {
		return x.VisibilityTimeout
	}
	return 0
}

// Message is delivered to consumers.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Attempt       uint32                 `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`                            // Delivery attempt number (1-based)
	PublishedAt   int64                  `protobuf:"varint,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // Unix timestamp millis
	OrderingKey   string                 `protobuf:"bytes,7,opt,name=ordering_key,json=orderingKey,proto3" json:"ordering_key,omitempty"`  // Ordering key (if set during publish)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_qwerq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Message) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *Message) GetOrderingKey() string {
	if x != nil {
		return x.OrderingKey
	}
	return ""
}

// AckRequest acknowledges a message.
type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_qwerq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// NackRequest negatively acknowledges (requeue).
type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Requeue       bool                   `protobuf:"varint,2,opt,name=requeue,proto3" json:"requeue,omitempty"` // If false, send to DLQ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_proto_qwerq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{5}
}

func (x *NackRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *NackRequest) GetRequeue() bool {
	if x != nil {
		return x.Requeue
	}
	return false
}

// ErrorResponse is sent on errors.
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_qwerq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SchemaRegisterRequest registers a schema for a queue.
type SchemaRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Descriptor_   []byte                 `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`                      // Protobuf FileDescriptorSet
	MessageType   string                 `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // Fully qualified message name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRegisterRequest) Reset() {
	*x = SchemaRegisterRequest{}
	mi := &file_proto_qwerq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRegisterRequest) ProtoMessage() {}

func (x *SchemaRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRegisterRequest.ProtoReflect.Descriptor instead.
func (*SchemaRegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{7}
}

func (x *SchemaRegisterRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *SchemaRegisterRequest) GetDescriptor_() []byte {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *SchemaRegisterRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

// SchemaRegisterResponse confirms registration.
type SchemaRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaId      uint32                 `protobuf:"varint,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRegisterResponse) Reset() {
	*x = SchemaRegisterResponse{}
	mi := &file_proto_qwerq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRegisterResponse) ProtoMessage() {}

func (x *SchemaRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRegisterResponse.ProtoReflect.Descriptor instead.
func (*SchemaRegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{8}
}

func (x *SchemaRegisterResponse) GetSchemaId() uint32 {
	if x != nil {
		return x.SchemaId
	}
	return 0
}

func (x *SchemaRegisterResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// CallRequest is RPC-style publish with reply.
type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs     uint32                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // How long to wait for reply
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_proto_qwerq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{9}
}

func (x *CallRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *CallRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// CallResponse is the reply to a Call.
type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_proto_qwerq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{10}
}

func (x *CallResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// SchemaListRequest requests all registered schemas.
type SchemaListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaListRequest) Reset() {
	*x = SchemaListRequest{}
	mi := &file_proto_qwerq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaListRequest) ProtoMessage() {}

func (x *SchemaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaListRequest.ProtoReflect.Descriptor instead.
func (*SchemaListRequest) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{11}
}

// SchemaInfo describes a registered schema.
type SchemaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaInfo) Reset() {
	*x = SchemaInfo{}
	mi := &file_proto_qwerq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaInfo) ProtoMessage() {}

func (x *SchemaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaInfo.ProtoReflect.Descriptor instead.
func (*SchemaInfo) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{12}
}

func (x *SchemaInfo) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *SchemaInfo) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *SchemaInfo) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// SchemaListResponse returns all registered schemas.
type SchemaListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*SchemaInfo          `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaListResponse) Reset() {
	*x = SchemaListResponse{}
	mi := &file_proto_qwerq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaListResponse) ProtoMessage() {}

func (x *SchemaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaListResponse.ProtoReflect.Descriptor instead.
func (*SchemaListResponse) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{13}
}

func (x *SchemaListResponse) GetSchemas() []*SchemaInfo {
	if x != nil {
		return x.Schemas
	}
	return nil
}

// QueueListRequest requests all queues.
type QueueListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueListRequest) Reset() {
	*x = QueueListRequest{}
	mi := &file_proto_qwerq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueListRequest) ProtoMessage() {}

func (x *QueueListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueListRequest.ProtoReflect.Descriptor instead.
func (*QueueListRequest) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{14}
}

// QueueInfo describes a queue.
type QueueInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MessageCount  uint32                 `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	InFlightCount uint32                 `protobuf:"varint,3,opt,name=in_flight_count,json=inFlightCount,proto3" json:"in_flight_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueInfo) Reset() {
	*x = QueueInfo{}
	mi := &file_proto_qwerq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInfo) ProtoMessage() {}

func (x *QueueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInfo.ProtoReflect.Descriptor instead.
func (*QueueInfo) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{15}
}

func (x *QueueInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueInfo) GetMessageCount() uint32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *QueueInfo) GetInFlightCount() uint32 {
	if x != nil {
		return x.InFlightCount
	}
	return 0
}

// QueueListResponse returns all queues.
type QueueListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*QueueInfo           `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueListResponse) Reset() {
	*x = QueueListResponse{}
	mi := &file_proto_qwerq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueListResponse) ProtoMessage() {}

func (x *QueueListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueListResponse.ProtoReflect.Descriptor instead.
func (*QueueListResponse) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{16}
}

func (x *QueueListResponse) GetQueues() []*QueueInfo {
	if x != nil {
		return x.Queues
	}
	return nil
}

// ExtendVisibilityRequest extends the visibility timeout for an in-flight message.
type ExtendVisibilityRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ExtensionSeconds uint32                 `protobuf:"varint,2,opt,name=extension_seconds,json=extensionSeconds,proto3" json:"extension_seconds,omitempty"` // Additional seconds to extend visibility
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtendVisibilityRequest) Reset() {
	*x = ExtendVisibilityRequest{}
	mi := &file_proto_qwerq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendVisibilityRequest) ProtoMessage() {}

func (x *ExtendVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendVisibilityRequest.ProtoReflect.Descriptor instead.
func (*ExtendVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{17}
}

func (x *ExtendVisibilityRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ExtendVisibilityRequest) GetExtensionSeconds() uint32 {
	if x != nil {
		return x.ExtensionSeconds
	}
	return 0
}

// ExtendVisibilityResponse confirms the extension.
type ExtendVisibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewVisibleAt  int64                  `protobuf:"varint,1,opt,name=new_visible_at,json=newVisibleAt,proto3" json:"new_visible_at,omitempty"` // New visibility timestamp (Unix millis)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendVisibilityResponse) Reset() {
	*x = ExtendVisibilityResponse{}
	mi := &file_proto_qwerq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendVisibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendVisibilityResponse) ProtoMessage() {}

func (x *ExtendVisibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qwerq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendVisibilityResponse.ProtoReflect.Descriptor instead.
func (*ExtendVisibilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_qwerq_proto_rawDescGZIP(), []int{18}
}

func (x *ExtendVisibilityResponse) GetNewVisibleAt() int64 {
	if x != nil {
		return x.NewVisibleAt
	}
	return 0
}

var File_proto_qwerq_proto protoreflect.FileDescriptor

const file_proto_qwerq_proto_rawDesc = "" +
	"\n" +
	"\x11proto/qwerq.proto\x12\x05qwerq\"\xd2\x02\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12<\n" +
	"\aheaders\x18\x03 \x03(\v2\".qwerq.PublishRequest.HeadersEntryR\aheaders\x12\"\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tH\x00R\tmessageId\x88\x01\x01\x12,\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tH\x01R\x0eidempotencyKey\x88\x01\x01\x12!\n" +
	"\fordering_key\x18\x06 \x01(\tR\vorderingKey\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_message_idB\x12\n" +
	"\x10_idempotency_key\"0\n" +
	"\x0fPublishResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"q\n" +
	"\x0eConsumeRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1a\n" +
	"\bprefetch\x18\x02 \x01(\rR\bprefetch\x12-\n" +
	"\x12visibility_timeout\x18\x03 \x01(\rR\x11visibilityTimeout\"\xab\x02\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x125\n" +
	"\aheaders\x18\x04 \x03(\v2\x1b.qwerq.Message.HeadersEntryR\aheaders\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\rR\aattempt\x12!\n" +
	"\fpublished_at\x18\x06 \x01(\x03R\vpublishedAt\x12!\n" +
	"\fordering_key\x18\a \x01(\tR\vorderingKey\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\n" +
	"AckRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"F\n" +
	"\vNackRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\arequeue\x18\x02 \x01(\bR\arequeue\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"p\n" +
	"\x15SchemaRegisterRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\fR\n" +
	"descriptor\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\"O\n" +
	"\x16SchemaRegisterResponse\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\rR\bschemaId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\"\xd3\x01\n" +
	"\vCallRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x129\n" +
	"\aheaders\x18\x03 \x03(\v2\x1f.qwerq.CallRequest.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\fCallResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12:\n" +
	"\aheaders\x18\x02 \x03(\v2 .qwerq.CallResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11SchemaListRequest\"_\n" +
	"\n" +
	"SchemaInfo\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\"A\n" +
	"\x12SchemaListResponse\x12+\n" +
	"\aschemas\x18\x01 \x03(\v2\x11.qwerq.SchemaInfoR\aschemas\"\x12\n" +
	"\x10QueueListRequest\"l\n" +
	"\tQueueInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\rR\fmessageCount\x12&\n" +
	"\x0fin_flight_count\x18\x03 \x01(\rR\rinFlightCount\"=\n" +
	"\x11QueueListResponse\x12(\n" +
	"\x06queues\x18\x01 \x03(\v2\x10.qwerq.QueueInfoR\x06queues\"e\n" +
	"\x17ExtendVisibilityRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12+\n" +
	"\x11extension_seconds\x18\x02 \x01(\rR\x10extensionSeconds\"@\n" +
	"\x18ExtendVisibilityResponse\x12$\n" +
	"\x0enew_visible_at\x18\x01 \x01(\x03R\fnewVisibleAtB+Z)github.com/jonas/qwer-q/internal/protocolb\x06proto3"

var (
	file_proto_qwerq_proto_rawDescOnce sync.Once
	file_proto_qwerq_proto_rawDescData []byte
)

func file_proto_qwerq_proto_rawDescGZIP() []byte {
	file_proto_qwerq_proto_rawDescOnce.Do(func() {
		file_proto_qwerq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qwerq_proto_rawDesc), len(file_proto_qwerq_proto_rawDesc)))
	})
	return file_proto_qwerq_proto_rawDescData
}

var file_proto_qwerq_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_qwerq_proto_goTypes = []any{
	(*PublishRequest)(nil),           // 0: qwerq.PublishRequest
	(*PublishResponse)(nil),          // 1: qwerq.PublishResponse
	(*ConsumeRequest)(nil),           // 2: qwerq.ConsumeRequest
	(*Message)(nil),                  // 3: qwerq.Message
	(*AckRequest)(nil),               // 4: qwerq.AckRequest
	(*NackRequest)(nil),              // 5: qwerq.NackRequest
	(*ErrorResponse)(nil),            // 6: qwerq.ErrorResponse
	(*SchemaRegisterRequest)(nil),    // 7: qwerq.SchemaRegisterRequest
	(*SchemaRegisterResponse)(nil),   // 8: qwerq.SchemaRegisterResponse
	(*CallRequest)(nil),              // 9: qwerq.CallRequest
	(*CallResponse)(nil),             // 10: qwerq.CallResponse
	(*SchemaListRequest)(nil),        // 11: qwerq.SchemaListRequest
	(*SchemaInfo)(nil),               // 12: qwerq.SchemaInfo
	(*SchemaListResponse)(nil),       // 13: qwerq.SchemaListResponse
	(*QueueListRequest)(nil),         // 14: qwerq.QueueListRequest
	(*QueueInfo)(nil),                // 15: qwerq.QueueInfo
	(*QueueListResponse)(nil),        // 16: qwerq.QueueListResponse
	(*ExtendVisibilityRequest)(nil),  // 17: qwerq.ExtendVisibilityRequest
	(*ExtendVisibilityResponse)(nil), // 18: qwerq.ExtendVisibilityResponse
	nil,                              // 19: qwerq.PublishRequest.HeadersEntry
	nil,                              // 20: qwerq.Message.HeadersEntry
	nil,                              // 21: qwerq.CallRequest.HeadersEntry
	nil,                              // 22: qwerq.CallResponse.HeadersEntry
}
var file_proto_qwerq_proto_depIdxs = []int32{
	19, // 0: qwerq.PublishRequest.headers:type_name -> qwerq.PublishRequest.HeadersEntry
	20, // 1: qwerq.Message.headers:type_name -> qwerq.Message.HeadersEntry
	21, // 2: qwerq.CallRequest.headers:type_name -> qwerq.CallRequest.HeadersEntry
	22, // 3: qwerq.CallResponse.headers:type_name -> qwerq.CallResponse.HeadersEntry
	12, // 4: qwerq.SchemaListResponse.schemas:type_name -> qwerq.SchemaInfo
	15, // 5: qwerq.QueueListResponse.queues:type_name -> qwerq.QueueInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_qwerq_proto_init() }
func file_proto_qwerq_proto_init() {
	if File_proto_qwerq_proto != nil {
		return
	}
	file_proto_qwerq_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qwerq_proto_rawDesc), len(file_proto_qwerq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qwerq_proto_goTypes,
		DependencyIndexes: file_proto_qwerq_proto_depIdxs,
		MessageInfos:      file_proto_qwerq_proto_msgTypes,
	}.Build()
	File_proto_qwerq_proto = out.File
	file_proto_qwerq_proto_goTypes = nil
	file_proto_qwerq_proto_depIdxs = nil
}
